### ISSUE TITLE
Assignable `__module__`  of `type` and `object`

### ISSUE THREAD

**Issue by sobolevn** [RustPython/RustPython#2766]
## Feature

CPython does not let to assign values to builtin types like `type`, `object`, `map`, etc.

```pycon
>>> type.__module__ = 'nope'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't set attributes of built-in/extension type 'type'

>>> object.__module__ = 'nope'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't set attributes of built-in/extension type 'object'
```

But, here's what `RustPython` does:

```pycon
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖
>>>>> type.__module__ = 'nope'
>>>>> object.__module__ = 'a'
```

Related #2310

## Python Documentation

---

**Comment by youknowone** [comment]
fixed by #2763

**Comment by sobolevn** [comment]
Nope, this is still happening with the latest `master`:
<img width="752" alt="Снимок экрана 2021-08-05 в 0 14 25" src="https://user-images.githubusercontent.com/4660275/128255798-8af1f4f2-33bc-4ef9-8724-9fca2731b98b.png">
